url: hellowac.github.io
author: hello wac
title: Hello Wac
description: "王超的网络日志"
show_downloads: false
create_time: 2017-01-11
# google_analytics: UA-90202913-1

github: { repository_name: hellowac.github.io, is_project_page: true, repository_url: 'https://github.com/hellowac/', owner_name: "wangchao", }

nav:
  home:
    name: '首页'
  blog:
    name: '日志'
    subnav:
      diary:
        name: '日记'
      english:
        name: '英语'
      programing:
        name: '编程'
      reading:
        name: '阅读'
  tags:
    name: '标签'
  projects:
    name: '项目'
  about:
    name: '关于'
  refer:
    name: '参考'

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
